### ISSUE TITLE
Feature request: allow to convert external images to base64 urls

### ISSUE THREAD

**Issue by ramarivera** [Sergei-Korneev/obsidian-local-images-plus#10]
As the title says, it would be another way of keeping images local.
What do you think?

**Comment by Sergei-Korneev** [comment]
Hi. I did not think about it. It is possible to implement, although I can see some shortcomings to this approach and it will take some amount of man/hours of course. According to you,  is there any particular reason a user might need this feature?

**Comment by ramarivera** [comment]
> According to you, is there any particular reason a user might need this feature? 

I can only speak for my case, but having images as base64 strings means somehow other operative system features won't index/preview the images. It is a very niche use case, I agree.

> I have tried to embed 600kb file. It had a big impact on Obsidian indexing performance. So I definitely won't implement this feature.

thank you for trying and reporting back, I didn't even think about obsidian indexing.
