### ISSUE TITLE
Process content from extenal links to the folder Vault/attachements/$(notename)/

### ISSUE THREAD

**Issue by MMMikeTr** [Sergei-Korneev/obsidian-local-images-plus#12]
Thanks for grate plugin! 
It is good to take control of all download images and content from web pages and use subfolders with $(notename) to storage them.
MarkDownloader can't download images to relative pathnames to actual 
" $(notename) " location. 
There for I've created a folder attachments in the root of Valt and it saves content of all markdown files from various folders in one specific location - Vault/attachements/$(TitleName) and it's work fine. 
While using you Pligin, I've found In you settings no option to use 'Media folder' not relative to the 
" $(notename) "
pathname, but only fixed location. Is it possible to add option to set hard path to 'Media folder' and not to use only ralative paths to " $(notename) " location?
Grate thanks!

**Comment by Sergei-Korneev** [comment]
Hi. Version 0.15.0 will have a more universal/intelligent way of assigning paths using templates. e.g. /myrootfolder/${date}/

**Comment by MMMikeTr** [comment]
Great!

**Comment by Sergei-Korneev** [comment]
Closing this as completed since the feature was implemented in 0.15.0
