### ISSUE TITLE
 Process content from local hard disk (originally located not in Vault) on copy-paste or drug-and-drop operations 

### ISSUE THREAD

**Issue by MMMikeTr** [Sergei-Korneev/obsidian-local-images-plus#13]
Thanks for grate plugin!
Is it possible to process on copy-paste or drug-and-drop operations for local hard disk content (originally located not in Vault) to storage them on Vault in hard paths like:
           " Vault/attachments/$(notename) "
location or relative to notes locations paths like:
           " ./attachemets/$(notename) "
?
It seems only rule from Settings->Files & Links->Default location for new attachments works and not any rules from Local Image Plus taking in order. 
Do we have any other solutions to achieve this goal?
Grate thanks!

**Comment by Sergei-Korneev** [comment]
Yes. It is possible in theory;)

**Comment by Sergei-Korneev** [comment]
Closing this as completed since the feature was implemented in 0.15.0
