### ISSUE TITLE
@in url , the file name is error

### ISSUE THREAD

**Issue by Hypdncy** [Sergei-Korneev/obsidian-local-images-plus#15]
url`https://pics1.baidu.com/feed/0ff41bd5ad6eddc42098b2247d5059f553663301.png@f_auto?token=22f6633d9fa0c5580825f68b0adbb352`

the name in md is 804e1e466ddd57e72df8bec098233375_MD5.png@f_auto
<img width="545" alt="image" src="https://user-images.githubusercontent.com/30820856/226195094-014fa163-3eff-41cc-93ed-ccf438e8cd1b.png">

**Comment by Sergei-Korneev** [comment]
晚上好。 It is strange to see @ in the url... I just updated the build 0.15.1 Should work now. Reinstall the plugin.

**Comment by Sergei-Korneev** [comment]
Closing this as completed since the bug  was fixed in 0.15.2
