### ISSUE TITLE
The safety issue of running this command globally on all the notes

### ISSUE THREAD

**Issue by Archie-2021** [Sergei-Korneev/obsidian-local-images-plus#16]
Hey guys,
I noticed that you warn users about applying this command to all the notes by mistake so you are aware of the problem, why nit adding an option in the settings to disabling it. If someone like me don't need it and is worried to hit it by mistake he can disable that option in the settings.

And thank you for this plugin, I am long time user of the old version of this plugin and just found out about the new version. I have been using "unique attachment plugin" and "MDlinks to Wikilinks" and QuickAdd to make macros and do what new version does with a single command. So I was pleasantly surprised today seeing this. Thank you very much.

**Comment by Sergei-Korneev** [comment]
Good point. Probably when I will have time to be at it again, I will add some modal window in new version.

**Comment by Sergei-Korneev** [comment]
Closing this as completed since the feature was implemented in 0.15.2
