### ISSUE TITLE
Unable to process gif file

### ISSUE THREAD

**Issue by shuojie819** [Sergei-Korneev/obsidian-local-images-plus#21]
I used sandbox warehouse testing.
Please check out my experimental video.

https://user-images.githubusercontent.com/72399630/236638531-8cdcda48-d7e5-468e-b70c-fee00b36e270.mp4

**Comment by Sergei-Korneev** [comment]
Hi. I have not been using windows these years. Is it a some standard image viewer of windows 11?

Also send me this gif file (if it does not contain some secret Chinese classified information ) so I could test it.

I am actually thinking of rewriting the clipboard algorithm completely. Cannot be giving promises though.

**Comment by shuojie819** [comment]
Yes, he is the standard image viewer for Windows11.
GIF file：[gif test file](https://user-images.githubusercontent.com/72399630/236806934-9d1ce1d9-7a63-45d3-abc1-8709a1e86822.gif)

> The reason why I use the standard image viewer is that it will make mistakes when copying directly in the file explorer.

https://user-images.githubusercontent.com/72399630/236808933-fe27c720-6805-4cd7-96ff-4020fdc4d9aa.mp4

**Comment by Sergei-Korneev** [comment]
Try new version.

**Comment by shuojie819** [comment]
Thanks, problem fixed.
