### ISSUE TITLE
how to automatically remove the attachments when delete the corresponding notes.

### ISSUE THREAD

**Issue by odljvkf** [Sergei-Korneev/obsidian-local-images-plus#24]
hi, 
I am wondering if there exist a solution that can automatically remove the attachments when delete the corresponding notes, or scan all the notes to determine whether some attachments should be removed or not.
cause when number of notes goes larger and larger and the tree structure of folders become more complex, it is hard to deal with the relationship between note and attachment when something goes wrong that needing fixed manually, such as image link or sync problems. In addition, it is also difficult to delete image and other things manually in lots of files when deleting notes to avoid storage space problems.
if there is a solution to solve this problem? if it already exists, please tell me.
thanks

**Comment by Sergei-Korneev** [comment]
Hi. Obsidian makes no distinction between regular files and attachments by default. If you use the same folder for all attachments you can use for example "Nuke Orphans" plugin or my [linux script](https://github.com/Sergei-Korneev/obsidian_orphan_mv)   to remove all orphaned files.
Or  you can try out these plugins:

https://github.com/pjeby/note-folder-autorename

https://github.com/dy-sh/obsidian-consistent-attachments-and-links


But it becomes more complicated when you download them to some other folder, e.g. in a folder relative to a note or some random folder where some "attachments" associated with several notes. In this case nobody even know if a file in that folder was once an "attachment" after you delete a note.  

Speaking of this plugin, of course it could check in folders configured in the plugin's settings and in the  default obsidian folder configured in the obsidian settings but it will not give you 100% guarantee of consistency.

**Comment by odljvkf** [comment]
hi,
  thanks for your reply.
  
  So, it seems that choosing one specified folder to save all attachments would be the only solution to avoid this problem. Cause as you mentioned above, when scale of the notes became very large, if putting attachments and images in different folders, even relative folder with the note (which can be chosen in this plugin), it will also cause huge mess when changing folder's structure or just moving some notes in or out some folders.
   
  I have searched some plugins that provide the service to delete unlinked attachments automatically, but some issues do point out that they will delete some useful attachments in some specific situation which is just as you said. Besides, they usually have a strong coupling with most of plugins, which will make it easily producing some horrible unrecoverable problem. 
  
  Anyhow, I am truly grateful for your suggestion, the plugin you suggested maybe the most workable plan to solve this problem, thanks again for your advice and this fantastic plugin.

**Comment by Sergei-Korneev** [comment]
You now can try the new version. Some new ideas have been represented there.

**Comment by odljvkf** [comment]
I see, the Orphaned attachments, that is a so great function, thanks a lot!
