### ISSUE TITLE
Sir, when I paste an image, it doesn't work sometimes.

### ISSUE THREAD

**Issue by xh542428798** [Sergei-Korneev/obsidian-local-images-plus#26]
I don't like the filename "Pasted XXXX", I hope obsidian-local-images-plus can rename the pasted image, but when I paste an image, it doesn't work sometimes, sometimes it works, what's the problem?

**Comment by Sergei-Korneev** [comment]
Hello, sir ;) Check if the folder you set in obsidian settings exists. Obsidian does not create it by default. In that case the plugin would not be able to find attachments to move them. Also you can try to show me the console output.

**Comment by xh542428798** [comment]
> Hello, sir ;) Check if the folder you set in obsidian settings exists. Obsidian does not create it by default. In that case the plugin would not be able to find attachments to move them. It would be more correct if you create some folder in the root of your vault and then select it in obsidian settings. Also you can try to show me the console output (ctrl + shift + I). .
> 
> Have a nice day.

Thank you for your prompt feedback. I noticed that some of the pasted images were not converted to code when I was taking notes. However, I am unable to reproduce the situation now. If I encounter this issue again in the future, I will do a detailed tracking. Thank you for your response and assistance.
