### ISSUE TITLE
[Feature request] Keep Download image use Markdown link not wikilink

### ISSUE THREAD

**Issue by Tback1** [Sergei-Korneev/obsidian-local-images-plus#29]
the old obsidian-local-images download the image use the markdownlink, Could add an option for the feature ？

md link have two advantages:
1 markdown_link can edit in VScode or Typora, wiki_link can't
2 markdown_link can "**name(annotation)**"  the picture，the wiki can't

**Comment by Sergei-Korneev** [comment]
This setting is now copied from Obsidian settings

![image](https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/60899505/c03c7aa9-68a2-4a8a-aa30-ab0a006b589b)

**Comment by Tback1** [comment]
I still need use wikilinks in obsidian,but not on image~
