### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by vapensmianm149s** [Sergei-Korneev/obsidian-local-images-plus#3]
https://mp.weixin.qq.com/s/e_0eezfDa94c_tbcF7UxJA
This page can not be downloaded correctly, there will be an incorrect replacement

**Comment by Sergei-Korneev** [comment]
Hey.  I was not be able to reproduce this. 

![image](https://user-images.githubusercontent.com/60899505/209685474-b6d8a0a2-77b0-4be4-b28a-76d6ab3a1efe.png)

Are you trying to copy all page at once or what? (there is still multithreading bug, which i am planning to fix in the future)
Send me your md file with replaced content , please.

**Comment by vapensmianm149s** [comment]
local images plus 0.14.4
obsidian V1.19 
win10
Remove obsidian-local-images plugin

[bug.zip](https://github.com/Sergei-Korneev/obsidian-local-images-plus/files/10311962/bug.zip)

**Comment by Sergei-Korneev** [comment]
You are talking about duplicates, right?
Try this pre-release, I just tried to download all images from that Chinese page, it took some time but worked.
(rename to file to .7z)
[obsidian_local_images_plus_0.14.5[pre-release].7z.zip](https://github.com/Sergei-Korneev/obsidian-local-images-plus/files/10312683/obsidian_local_images_plus_0.14.5.pre-release.7z.zip)

**Comment by vapensmianm149s** [comment]
right,The bug was fixed.

good job ,thanks
