### ISSUE TITLE
which command is for download images in current markdown note?

### ISSUE THREAD

**Issue by francisHugo** [Sergei-Korneev/obsidian-local-images-plus#30]
I am confused by the command 1 and 2 in blow image, what's the difference between of these two commands?

in addition, what if I just want to download images or media files for the current markdown note? which command should I chose?

![image](https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/129242259/2b5cd573-bbc9-4f45-81bb-43c74dbe994c)

best regards
Francis H

**Comment by Sergei-Korneev** [comment]
Hey, Francis. Just updated the readme. Read it carefully. Closing this.
