### ISSUE TITLE
It doesn't work when renaming image names using MD5 is disabled and you want to keep the original image names and resource directory names

### ISSUE THREAD

**Issue by zhouxinghong** [Sergei-Korneev/obsidian-local-images-plus#31]
It doesn't work when renaming image names using MD5 is disabled and you want to keep the original image names and resource directory names
![image](https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/54253524/93d69c02-54e8-44ff-96af-b691625c65d2)

1.3.5
0.15.7
Windows10
When I disable rename image names with MD5 and want to keep the original image names vs resource directory names, it doesn't work, it always renames image names with resource directory names using MD5 which is very frustrating. I hope you can fix this error in time, thank you very much for your excellent extension. 👍😜
![image](https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/54253524/2e773956-cbfc-44cd-ac19-5fa756a35ec3)
Because such a file path looks very incomprehensible😒

**Comment by Sergei-Korneev** [comment]
Hi, I cannot see a screencast etc in your issue. If you are trying this setting when downloading images, keep in mind, that this setting only applies to inserted attachments, not to uploaded ones. This behavior was implemented on purpose.  There is no 100% reliable way to find the original file name on a server.

**Comment by zhouxinghong** [comment]
I can understand what you are saying.
But I have some ideas.
1. It is recommended to use date and time stamps or incremental numbers for image file naming, maybe it will be better to understand.
2. Suggest keeping the name of the original resource directory and not base64 encoding the name of the original resource directory, this would also be better.
3. It is suggested to provide an option to allow users to turn off auto-replacement to local image files (only download network image files, but not auto-replace to local image files, so as to keep it updated with online image resources in real time).
Also I will upload screenshots to you again.

**Comment by zhouxinghong** [comment]
I have turned off MD5
![image](https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/54253524/93d69c02-54e8-44ff-96af-b691625c65d2)
Because such a file path looks very incomprehensible😒
![image](https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/54253524/2e773956-cbfc-44cd-ac19-5fa756a35ec3)

**Comment by Sergei-Korneev** [comment]
> I can understand what you are saying.

You obviously do not. Sorry. Or it is just me can not understand you English.

See my message above.

> This behavior was implemented on purpose. There is no 100% reliable way to find the original file name on server.

I once had an idea to name files after anchor (if it is not empty, which happens pretty often in md fies), but it also requires some amount of time to implement

**Comment by zhouxinghong** [comment]
I can understand what you are saying.
But I have some ideas.

1. suggest to use hour, minute, millisecond or timestamp or incremental numbers to name the image files, maybe it will be better to understand.
2. suggest to keep the name of the original resource directory instead of base64 encoding the name of the original resource directory, that would also be better.
3. Suggest providing an option to allow users to turn off auto-replacement to local image files (i.e., only download web image files, but do not auto-replace to local image files to keep the online image resources updated in real time) 👍.

**Comment by zhouxinghong** [comment]
MD5 is used for encryption, but as a unique identifier I don't think it's the most ideal solution
MD5是用於加密的，但是作為唯一標識我認為不是最理想的方案

**Comment by zhouxinghong** [comment]
MD5 is used for encryption, but as a unique identifier I don't think it's the most ideal solution
I know the most ideal way to rename files is to use: hour, minute, and second and to time to milliseconds, because many similar software also use this batch file naming scheme, you may consider whether to use such a scheme.
Of course there are also schemes like GUID or UUID etc....
MD5是用於加密的，但是作為唯一標識我認為不是最理想的方案
我認識最理想的方式是使用：時分秒並將時間精確到毫秒的方式來重命名文件，因為很多類似的軟件也是採用這種批量文件命名的方案，您可以考慮是否採用這樣的方案。
當然還有GUID或者UUID這種方案等等。 。 。

**Comment by Sergei-Korneev** [comment]
> suggest to keep the name of the original resource directory instead of base64 encoding the name of the original resource directory, that would also be better.

It not base64, it is called URI

> MD5 is used for encryption, but as a unique identifier I don't think it's the most ideal solution

1 MD5 is for hashing, not for encrypting

2 You are free to implement your own solution. Good luck.

**Comment by zhouxinghong** [comment]
I do not know JavaScript and other web technologies, or I could also create a similar extension

**Comment by zhouxinghong** [comment]
There is actually a simpler implementation of file naming:
1. if the file does not exist in the directory then direct downloading;
2. if the file exists in a directory then download it for the file name + 1;
The name of the file for a batch download, e.g:
myflle.jpg
myflle01.jpg
myflle02.jpg
myflle03.jpg
...

**Comment by Sergei-Korneev** [comment]
Holy cow.... Are serious? :D Or it is just trolling.

**Comment by Sergei-Korneev** [comment]
> Because such a file path looks very incomprehensible

Btw , you can use wikilinks mode. It does not require URI  in URL.  Thanks for your profound thoughts and advices ;) Will close this later.
