### ISSUE TITLE
After disabling the plugin, it continues to run in the background. 

### ISSUE THREAD

**Issue by Kirill-ver** [Sergei-Korneev/obsidian-local-images-plus#33]
Uninstalling it doesn't help either. Please advise how to solve this problem.
![Screenshot_1](https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/138564506/1e2cbfb3-22b0-492e-996a-b222fb98b305)
![Screenshot_2](https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/138564506/9f8e55f2-e732-4515-a66a-5a8b22e43489)
![Screenshot_3](https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/138564506/3cc35668-a612-4e21-9844-6483e82c3b64)

**Comment by Sergei-Korneev** [comment]
restart Obsidian

**Comment by Kirill-ver** [comment]
Yes, it worked, thank you so much))))))
