### ISSUE TITLE
how to not use the _MD5 as the suffix of the filename?

### ISSUE THREAD

**Issue by Tback1** [Sergei-Korneev/obsidian-local-images-plus#34]
I still need use wikilinks in obsidian,but not on image~

and by the way how to not use the **_MD5** as the suffix of the filename?
![image](https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/8872546/4dc40a0d-b3a8-4eae-901b-92387e5d68f9)

I use the MD5 as the filename but not need the suffix. could add this?
![image](https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/8872546/8bc18bec-bc4b-4d5e-b919-27a7c37965a2)

_Originally posted by @Tback1 in https://github.com/Sergei-Korneev/obsidian-local-images-plus/issues/29#issuecomment-1613535086_

**Comment by Sergei-Korneev** [comment]
> and by the way how to not use the _MD5 as the suffix of the filename?

>  I still need use wikilinks in obsidian,but not on image~


You are allowed to edit the source-code.
