### ISSUE TITLE
the command 【Download all media files (Plugin folder)】 should be changed to 【Download all media files (Plugin folder) for current note】

### ISSUE THREAD

**Issue by calmwaves111** [Sergei-Korneev/obsidian-local-images-plus#38]
The current description of this command is confusing
the command 【Download all media files (Plugin folder)】 should be changed to 【Download all media files (Plugin folder) for current note】
the command 【Download all media files (Obsidian folder)】 should be changed to 【Download all media files (Obsidian folder) for current note】

**Comment by Sergei-Korneev** [comment]
You are free to edit the source code ;)

**Comment by calmwaves111** [comment]
you are right, I can do it
![image](https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/56907077/b23bdbd0-36d3-45cc-af71-6412573b3535)

**Comment by Sergei-Korneev** [comment]
Good luck.
