### ISSUE TITLE
"Remove all orphaned atachemnts" doesn't find any images

### ISSUE THREAD

**Issue by pacyfist** [Sergei-Korneev/obsidian-local-images-plus#39]
I separated my notes by theme into folders and I wanted each theme to have it's own "shared" image folder, so I configured the plugin like so:
![obraz](https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/2545509/15f3365f-1367-4548-aded-7c61242ca067)

Unfortunately in this case "Remove all orphaned atachemnts" doesn't find any attachments since the "plugin" setting requires this condition to be fulfilled, and I don't have `${notename}` present.

```ts
if (noteFile.path.match(includeRegex) &&
  path.basename(oldRootdir).includes("${notename}") &&
  !oldRootdir.includes("${date}")) {
```

**Comment by Sergei-Korneev** [comment]
Yep, all right. So the plugin works as intended. And how that is an "issue"?  
![image](https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/60899505/925f89b6-fabc-4a59-bfdf-58a522eb5902)

**Comment by Sergei-Korneev** [comment]
Will change add the notification to warn some unwitting users in the next version.
