### ISSUE TITLE
[Feature Request] support formatting of the placeholder {date}

### ISSUE THREAD

**Issue by coolbq** [Sergei-Korneev/obsidian-local-images-plus#40]
Hi, if the plugin supports formatting the {date} variable by the [Moment format options](https://momentjscom.readthedocs.io/en/latest/moment/04-displaying/01-format/), it will help alot.

**Comment by euzenlee** [comment]
also need it.

**Comment by ehamon** [comment]
sorting folders by YYYYMMDD will be fine indeed

**Comment by ehamon** [comment]
> edit main.js //const current_date = date.getDate() + "." + (date.getMonth() + 1) + "." + date.getFullYear(); const current_date = date.getFullYear().toString()+ (date.getMonth() + 1).toString().padStart(2,'0') + date.getDate().toString().padStart(2,'0');

Works fine! Merci

**Comment by Sergei-Korneev** [comment]
This feature was implemented in 0.16.0 Wait for the release. Closing this.
