### ISSUE TITLE
Bug report: Local images plus isn't processing images

### ISSUE THREAD

**Issue by doniv79** [Sergei-Korneev/obsidian-local-images-plus#44]
I'm facing a serious issue with the plugin simply not working as expected on a vault. It processes the file and says "Page xx has been processed, and nothing has been changed". The vault is synced with Obsidian Sync. Another vault with the plugin works as expected, however. I verified that the plugins installed in each vault are identical and the settings page for Local Images Plus is also identical across the vaults. I've tried uninstalling and installing the plugin in the problematic vault multiple times, but I'm still facing the issue. I can see the plugin make a folder for the note name per the configuration, but it's not renaming the file with the MD5 hash and moving it to the newly-created folder. What are other things I could try to debug this issue?

Obsidian version: Version 1.4.14
Local images plus version: 0.15.7
macOS version: 13.5.2 (22G91)

**Comment by Sergei-Korneev** [comment]
You can record a screen cast with all your actions step-by-step:

- Disable all other plugins
- Open console (CTRL+SHIFT+I)
- Open a note you would like to process
- Switch the note into the "Source mode"
- Run command
- Share the video here.

But still, I should mention, that I do not have neither  MacOS, nor Obsidian-Sync.

**Comment by doniv79** [comment]
https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/2527565/6a3fa343-37e4-454e-acef-e902e9a8bdc4

Here you go. Nothing's showing up in the console even though I've enabled verbose logging, unfortunately.

**Comment by Sergei-Korneev** [comment]
Show me this settings on both vaults

![image](https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/60899505/f61097fa-9465-4b56-a779-0baad3e24709)

**Comment by doniv79** [comment]
I was referring to the verbose logging option in the console. The setting for "Default location for new attachments" was different. When I switched it to "Vault folder", the plugin started working! Thanks!
