### ISSUE TITLE
It doesn't effect when pictures are “webp” format [bug]

### ISSUE THREAD

**Issue by srun007** [Sergei-Korneev/obsidian-local-images-plus#49]
**Is your feature request related to a problem? Please describe.**
It doesn't effect when pictures are “webp” format.  It works when the format are png & jpeg, but when copy a batch pictures from internet , the default format become webp, and the rules uneffect!

**Describe the solution you'd like**
hope to support webp format , especially copy a batch pictures from internet!

**Describe alternatives you've considered**
when copy some words and pictures more than one , the format changed, from png or jpeg become webp, and rename rules useless

**it works when copy a single png picture**
![image](https://github.com/reorx/obsidian-paste-image-rename/assets/80263694/d53840d9-8a9c-41f7-b6ec-39d0017d9bdf)

**It doesn't effect when pictures are “webp” format  (copy more pictures become webp format)**
![image](https://github.com/reorx/obsidian-paste-image-rename/assets/80263694/ed52c311-37f6-4fbf-bdd6-8dd4b4250260)

![image](https://github.com/reorx/obsidian-paste-image-rename/assets/80263694/0ee0f4aa-12d6-4e2e-81b5-7f9c28a8d2b5)

**Comment by Sergei-Korneev** [comment]
The plugin converts png to jpeg , what it has to do with webp...
To be honest I cannot understand a thing. 
See how to write bug reports:
https://marker.io/blog/how-to-write-bug-report
