### ISSUE TITLE
The setting option “save attachment next to the note" should be self-defined

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [Sergei-Korneev/obsidian-local-images-plus#5]
hello,

First I must say this is a nice plugin and provides the option to save attachments next to the note. But the output destination is immutable: `{note_name}.md_res`. 

Could this plugin add another option that can read the obsidian default option for new attachments, like below

![image](https://user-images.githubusercontent.com/11333496/210373367-84fdf1fa-9c57-4a91-ad62-2f6e7417db44.png)

**Comment by Sergei-Korneev** [comment]
Hello. Yes, in version 0.14.6 I will probably  add drop-down menu with several options.    Would you please tell me a little bit more about what directory structure  would you like to see in your vault?

**Comment by christophberger** [comment]
I second @ZhengshuaiPENG's suggestion. Is it technically possible that a plugin can read the attachment settings from the user's preference? 

I would love to have the media downloaded into the configured attachment folder.

**Comment by Sergei-Korneev** [comment]
@christophberger Yes, it is possible.

**Comment by christophberger** [comment]
Oooh that sounds good!

**Comment by feedhopper** [comment]
YES, self defined would be GREAT!

I would very much prefer to have all files inside subfolders. The question is: WHERE should they be?

1. I would not like to have subfolders cluttering my folder structure. This surely leads to a file explorer status less desirable to read and navigate
2. Mostly, I am fine with images and such sitting inside my attachment folder. It is tucked away in a folder called zzz/attachment which sorts itself to the very bottom of my file explorer.
3. It would be great to have an option to create subfolders inside this attachment folder. I hate everything sitting in one giant folder. It is a pain to sift through when there are several thousands of items and t's only a question of time that this becomes a problem on the file system(s: Windows & Android).
4. Another interesting issue: How to deal with items linked to from several notes? I would prefer to have it sorted in one folder only, ideally in the first one i.e. where the originated from.

Oh... and what I didn't say: THANK YOU for refurbishing this plugin. I use its predecessor a LOT and also noticed a couple of feature in need of polishing.

**Comment by Sergei-Korneev** [comment]
Closing this as completed since the feature was implemented in 0.14.8
