### ISSUE TITLE
Is there any way to keep the converted images not to change there's width and height in markdown files?

### ISSUE THREAD

**Issue by odljvkf** [Sergei-Korneev/obsidian-local-images-plus#55]
hi, when I paste copy into obsidian's markdown files, this plugin will auto transform image URL into local attachment, btw thanks a lot for this fantastic plugin. However, the image's height and width will change after they become local attachments and its link, so when some mathematic signals are placed in image in website, it will lead to some problems. Is there any solution to avoid this kind of problem?
like this:
![image](https://user-images.githubusercontent.com/85918343/282208311-c16b914c-fa4d-4ab2-81b2-22fd13a66c20.png)
converted:
![image](https://user-images.githubusercontent.com/85918343/282208341-25d1fb2a-7c61-483e-a518-eb186b10a0ba.png)

**Comment by Sergei-Korneev** [comment]
Google html / css / markdown ;)

**Comment by odljvkf** [comment]
Thanks for answer, I see what you mean. However, the problem does not involve in CSS, just the same .SVG html URL link parsed into different view size in obsidian's markdown files, whether they are in the paragraph or not, or whether converted by plugin (more easily happen when converted).

Finally found that this problem was due to an appearance theme (minimal) 🥹. 
(not sure whether can be solved by changing minmal settings, perhaps need to customize CSS file)
