### ISSUE TITLE
Localizing images destroys tables

### ISSUE THREAD

**Issue by gerroon** [Sergei-Korneev/obsidian-local-images-plus#60]
Hi

I like this plugin a lot but there is a downside. It destroys tables if the images are in tables. You can test it with the page below yoursel. Copy and paste the page then run  localize attahcments

https://github.com/nerdyrodent/AVeryComfyNerd

**Comment by Sergei-Korneev** [comment]
Just do not use wikilinks mode for tags

**Comment by gerroon** [comment]
Are you sure about ti? I already disabled  wikilinks. Did you get to try it with the link I provided?

**Comment by Sergei-Korneev** [comment]
Yes, I've tried it   
![image](https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/60899505/33a11cba-5d97-4e1a-b3f6-128b02394e8b)
![image](https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/60899505/2b8ea015-90fc-40c6-90fe-d3dd6a2a382a)

**Comment by Sergei-Korneev** [comment]
And on top of that I do not even know  what do you mean by "destroys tables"   See how to write bug reports https://marker.io/blog/how-to-write-bug-report
