### ISSUE TITLE
[Feature request] Ability to use date variables in Media folder name

### ISSUE THREAD

**Issue by notDavid** [Sergei-Korneev/obsidian-local-images-plus#63]
Hi there,

Please consider implementing the ability to set the `Media folder` to for example `assets/${date:YYYY}/${notename}`

(Currently, it is not accepting the `${date:YYYY}` variable.)

Thank you!

**Comment by Sergei-Korneev** [comment]
Duplicate https://github.com/Sergei-Korneev/obsidian-local-images-plus/issues/40
