### ISSUE TITLE
The plugin will generate two adjacent duplicate links from the image link.

### ISSUE THREAD

**Issue by xjl456852** [Sergei-Korneev/obsidian-local-images-plus#64]
Sometimes when I paste a lot of graphic content, the plugin will generate two adjacent duplicate links from the image link.
like this:

```
 [Open: Pasted image 20240119220855.png](_resources/19.1.2024/7908e2c299f807e15ce2c4293ed602e8_MD5.jpeg)
![](_resources/19.1.2024/7908e2c299f807e15ce2c4293ed602e8_MD5.jpeg)
```

**Comment by Sergei-Korneev** [comment]
![image](https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/60899505/ec957ae7-d4d9-4a8a-b289-3ca10e5882c5)
