### ISSUE TITLE
Exclusions not always working?

### ISSUE THREAD

**Issue by vukisz** [Sergei-Korneev/obsidian-local-images-plus#67]
I added these exclusion file types:
pdf|cnt|php|htm|html|xml|xpo|zip|rar|vssettings|xsl|xslt

Now drag and dropping file "Exported-2024-03-06.vssettings" does changes:
![image](https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/48272340/fec1c136-a69a-4b5f-a3e5-4cc246b2c9cb)

Resulting with skewed file name:
![image](https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/48272340/0f4eb11b-4b21-4113-83b1-0471380c8c12)

**Comment by Sergei-Korneev** [comment]
Hello. As far as can remember, this setting is not for local files  only.

**Comment by Sergei-Korneev** [comment]
I added it  to not download some web files.

**Comment by vukisz** [comment]
Hi @Sergei-Korneev is there a setting not to execute this this plugging when drag and dropping files from local PC?

**Comment by Sergei-Korneev** [comment]
You can disable MD5 for all files, the plugin will work almost the same way except not generating unique names for pasted files.
