### ISSUE TITLE
The src attribute in the img tag cannot be correctly converted; after conversion, it still uses the online URL.

### ISSUE THREAD

**Issue by Sault-water-water** [Sergei-Korneev/obsidian-local-images-plus#68]
The src attribute in the img tag cannot be correctly converted; after conversion, it still uses the online URL.
![image](https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/109705629/e7bd2335-7ee9-4f20-bcc0-9f5a9d3cfe19)
![image](https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/109705629/b3dfeb73-8841-4c75-a7f7-586969dfa013)

**Comment by Sergei-Korneev** [comment]
And again... This issue  has not been formed correctly so I cannot understand a thing. 

This plugin does not work with html, but it has a command to convert  html to markdown.
