### ISSUE TITLE
Original image does not get deleted when renamed

### ISSUE THREAD

**Issue by SchittBull** [Sergei-Korneev/obsidian-local-images-plus#73]
When pasting an image from the clipboard, the plugin creates a copy and renames the copy but the original pasted image will still be in the note and on my hard drive. This was not always like this and I don't know what changed.

[Screencapture Video](https://github.com/Sergei-Korneev/obsidian-local-images-plus/assets/53765158/2d88d3d4-a877-4456-b340-cd36fc476ab9)

**Comment by Sergei-Korneev** [comment]
It is just the original name. Try this setting 
![image](https://github.com/user-attachments/assets/5cc9ec87-4489-4805-a28f-4c43e5cee44e)
