### ISSUE TITLE
Error on slight format change.

### ISSUE THREAD

**Issue by EllriNidhogg** [Sergei-Korneev/obsidian-local-images-plus#9]
\!\[An axial leaded NTC](https://eepower.com/uploads/education/ntc_thermistor_axial_100px.jpg "Axial leaded NTC") is a valid link format that gives the "description" on mouse over. The converted file would be ![[ntc_thermistor_axial_100px.jpg|"Axial leaded NTC"]]. For reference the pipe also allows for resizing the image if it is a number instead of a string.
Currently this just errors out.
An option to keep the \[name|"description"](ntc_thermistor_axial_100px.jpg) format would be nice if possible as well.

**Comment by Sergei-Korneev** [comment]
Hi.  First, I cannot find any errors when processing your link. 

![image](https://user-images.githubusercontent.com/60899505/214763453-47e050ef-3521-460c-89a1-6075a386a7df.png)
![image](https://user-images.githubusercontent.com/60899505/214763489-f0715b6a-b548-4e09-b0e8-f09458943d20.png)

Second, Obsidian does not support image captions out of the box yet (as far as I know).

A link in format:
![image](https://user-images.githubusercontent.com/60899505/214763756-cb5d15a1-e073-4a29-a416-e1a2f79ec97a.png)
Will give you just this:
![image](https://user-images.githubusercontent.com/60899505/214763819-d5f01340-f979-47e6-a15b-0e553abe4c3e.png)

With that beign said,   maybe if you provide more information about your use case I will think about adding some features in the next versions.

**Comment by Sergei-Korneev** [comment]
Closing this as completed since the feature was implemented in 0.14.9
